name: PHP CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  php-ci:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
 
    - name: Run PHP Unit Tests
      run: |
        php -d memory_limit=-1 /github/workspace/getsource.php
